[package]
name = "modelo3D"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
image = "0.25.2"
minifb = "0.27.0"
nalgebra-glm = "0.19.0"
once_cell = "1.19.0"
rand = "0.8.5"
rodio = "0.19.0"
rayon = "1.5"
tobj = "4.0.2"